clc
clear
close all
BC=imread('BC.jpg');
AC=imread('AC.jpg');
BF=imread('BF.jpg');
AF=imread('AF.jpg');
BB=imread('BB.jpg');
AB=imread('AB.jpg');
tic
myTolerance=4;
[optimizer,metric]=imregconfig('multimodal');
optimizer.InitialRadius=optimizer.InitialRadius/35;
optimizer.MaximumIterations=3000;
ACR=Register(AC,BC,optimizer,metric);
imshowpair(ACR,BC)
saveas(gcf,'ACR.jpg')
CM=detectDamage(BC,ACR,myTolerance);
CD=showDamage(ACR,CM,[255,0,0]);
figure
imshow(CD)
imwrite(CD,'CD.jpg')
BFR=Register(BF,BC,optimizer,metric);
figure
imshowpair(BFR,BC)
saveas(gcf,'BFR.jpg')
AFR=Register(AF,BC,optimizer,metric);
figure
imshowpair(AFR,BC)
saveas(gcf,'AFR.jpg')
FM=detectDamage(BFR,AFR,myTolerance);
FD=showDamage(AFR,FM,[255,0,0]);
figure
imshow(FD)
imwrite(FD,'FD.jpg')
BBR=Register(BB,BC,optimizer,metric);
figure
imshowpair(BBR,BC)
saveas(gcf,'BBR.jpg')
ABR=Register(AB,BC,optimizer,metric);
figure
imshowpair(ABR,BC)
saveas(gcf,'ABR.jpg')
BM=detectDamage(BBR,ABR,myTolerance);
BD=showDamage(ABR,BM,[255,0,0]);
figure
imshow(BD)
imwrite(BD,'BD.jpg')
[OD,VD]=showOverallDamage(ABR,CM,[255,0,0],FM,[0,255,0],BM,[0,0,255],[255,0,0]);
figure
imshow(OD)
imwrite(OD,'OD.jpg')
figure
imshow(VD)
imwrite(VD,'VD.jpg')
toc